amazon:
  dynamodb:
    endpoint: "http://localhost:8000"

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

  main:
    allow-bean-definition-overriding: true
  mvc:
    log-request-details: true
  mustache:
    suffix: .html
server:
  port: 9000
  tomcat:
    mbeanregistry:
      enabled: true


logging:
  config: classpath:log4j2.xml